<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cognav_bt_behaviors</name>
  <version>0.0.0</version>
  <description>Behaviour tree leaves for the CogNav runner.</description>
  <maintainer email="mahsa.nikmard@gssi.it">Mahsa Nikmard</maintainer>
  <author email="mahsa.nikmard@gssi.it">Mahsa Nikmard</author>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>cognav_representation</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
